# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "environment-states"
    key                  = "vs-enterprise/staging/global/resource_groups/terraform.tfstate"
    resource_group_name  = "rg-terragrunt-example-001"
    storage_account_name = "stterragruntexample001"
    subscription_id      = "04b60e30-ab01-42ad-8cc9-eb2b2c55ff5b"
  }
}
