# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        azurerm = {
          source = "hashicorp/azurerm"
          version = "2.95.0"
        }
        azuread = {
            source = "hashicorp/azuread"
            version = "2.18.0"
        }
      }
    }

    provider "azurerm" {
        features {}
        subscription_id = "04b60e30-ab01-42ad-8cc9-eb2b2c55ff5b"
    }

    provider "azuread" {
    }
